name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Download artifact from another workflow (docs.yml)
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: DocumentationHTML
          path: ${{ github.workspace }}

  deploy:
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Deploy the built site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: docs/
          token: ${{ secrets.GITHUB_TOKEN }}